# Generated by Django 3.1.5 on 2021-02-10 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hello', '0002_auto_20210210_1001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='message',
            new_name='subject',
        ),
    ]
